const STORE='gowla_v32_news';
const REP_STORE='gowla_v32_reporters';
const seed=[
{id:1,title:'جولة تتابع آخر المستجدات من الميدان',category:'محلي',excerpt:'تغطية مستمرة لأبرز الأحداث والوقائع مع تحديثات من مراسلي جولة.',body:'تتابع قناة جولة الحدث من الميدان وتنقل التفاصيل أولاً بأول.',image:'assets/studio.jpg',status:'published',breaking:true,featured:true,views:1840,time:'الآن',reporter:'أحمد محمد'},
{id:2,title:'تغطية ميدانية: تفاصيل جديدة من قلب الحدث',category:'تغطيات جولة',excerpt:'مراسلو جولة في الميدان لنقل الصورة كاملة.',body:'تقرير ميداني مصور يضع الحدث في سياقه.',image:'assets/studio.jpg',status:'published',breaking:false,featured:true,views:1320,time:'قبل 18 دقيقة',reporter:'محمد عمر'},
{id:3,title:'قصة إنسانية من المجتمع: حين تتحول المبادرة إلى أثر',category:'مجتمع',excerpt:'قصص الناس والمبادرات التي تصنع فرقاً حقيقياً.',body:'قصة إنسانية من المجتمع المحلي.',image:'assets/studio.jpg',status:'published',breaking:false,featured:false,views:980,time:'قبل 42 دقيقة',reporter:'سارة أحمد'},
{id:4,title:'تقرير جولة: قراءة في المشهد وأبرز ما يجب معرفته',category:'تقارير',excerpt:'سياق وتحليل ومصادر تساعدك على فهم القصة.',body:'تقرير تحليلي من إعداد فريق جولة.',image:'assets/studio.jpg',status:'published',breaking:false,featured:false,views:760,time:'قبل ساعة',reporter:'علي إبراهيم'}
];
const seedReps=[['أحمد محمد','مراسل ميداني','الوسط'],['محمد عمر','مراسل جولة','الشرق'],['علي إبراهيم','مراسل وتصوير','الغرب'],['سارة أحمد','محررة ميدانية','الشمال']].map((r,i)=>({id:i+1,name:r[0],role:r[1],region:r[2],active:true}));
function read(key, fallback){try{const x=JSON.parse(localStorage.getItem(key));if(Array.isArray(x)&&x.length)return x;}catch{} localStorage.setItem(key,JSON.stringify(fallback));return fallback;}
function get(){return read(STORE,seed)} function reps(){return read(REP_STORE,seedReps)} function put(x){localStorage.setItem(STORE,JSON.stringify(x))} function putReps(x){localStorage.setItem(REP_STORE,JSON.stringify(x))}
const $=s=>document.querySelector(s); let current='dashboard',editId=null;
function esc(v=''){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function boot(){ $('#login').classList.add('hidden');$('#shell').classList.remove('hidden');$('#who').textContent='وضع تجريبي محلي • جاهز للمعاينة';$('#role').textContent='V3.2';render(); }
$('#logout').onclick=()=>location.href='/'; if($('#loginBtn'))$('#loginBtn').onclick=()=>boot();
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{current=b.dataset.view;editId=null;document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');render()});
function render(){if(current==='dashboard')dashboard();if(current==='articles')articles();if(current==='new')form();if(current==='reporters')reporters();}
function dashboard(){const a=get();const pub=a.filter(x=>x.status==='published');$('#title').textContent='نظرة عامة';$('#view').innerHTML=`<div class="content"><div class="notice"><b>V3.2</b> — غرفة أخبار محسّنة للمعاينة. يمكنك إنشاء الأخبار، رفع الصور من الهاتف، تحديد عاجل/رئيسي، ربط المراسل، والبحث والتصفية. البيانات محفوظة محليًا في هذا المتصفح إلى حين الربط بقاعدة بيانات حقيقية.</div><div class="stats"><div class="stat"><b>${pub.length}</b><span>منشور</span></div><div class="stat"><b>${a.filter(x=>x.status==='draft').length}</b><span>مسودات</span></div><div class="stat"><b>${a.filter(x=>x.breaking).length}</b><span>عاجل</span></div><div class="stat"><b>${a.reduce((s,x)=>s+Number(x.views||0),0).toLocaleString('ar')}</b><span>مشاهدة</span></div></div><div class="panel"><div class="panel-title"><h2>آخر المواد</h2><button class="btn" onclick="current='new';editId=null;render()">+ خبر جديد</button></div>${a.slice().sort((x,y)=>y.id-x.id).slice(0,8).map(x=>`<div class="tr"><span class="badge ${x.status}">${x.status==='published'?'منشور':x.status==='draft'?'مسودة':'مجدول'}</span><span>${esc(x.title)}</span><span class="hide">${esc(x.category)}</span><span>${Number(x.views||0).toLocaleString('ar')} مشاهدة</span></div>`).join('')}</div></div>`}
function articles(){const a=get();$('#title').textContent='الأخبار';$('#view').innerHTML=`<div class="content"><div class="toolbar"><div><h2>إدارة الأخبار</h2><small>${a.length} مادة في الأرشيف المحلي</small></div><button class="btn red" onclick="current='new';editId=null;render()">+ خبر جديد</button></div><div class="filters"><input id="searchArticles" placeholder="ابحث في العناوين..." oninput="filterArticles()"><select id="filterStatus" onchange="filterArticles()"><option value="">كل الحالات</option><option value="published">منشور</option><option value="draft">مسودة</option><option value="scheduled">مجدول</option></select><select id="filterCat" onchange="filterArticles()"><option value="">كل التصنيفات</option>${['محلي','السودان','العالم','تغطيات جولة','توثيق','تقارير','مجتمع','فيديو'].map(c=>`<option>${c}</option>`).join('')}</select></div><div id="articleTable" class="table"></div></div>`;filterArticles()}
function filterArticles(){const a=get();const q=($('#searchArticles')?.value||'').toLowerCase();const st=$('#filterStatus')?.value||'';const cat=$('#filterCat')?.value||'';const list=a.filter(x=>(!q||x.title.toLowerCase().includes(q))&&(!st||x.status===st)&&(!cat||x.category===cat));$('#articleTable').innerHTML=`<div class="tr head"><span>الحالة</span><span>العنوان</span><span>التصنيف</span><span>إجراء</span></div>`+list.map(x=>`<div class="tr"><span><i class="dot ${x.breaking?'red-dot':''}"></i>${x.status==='published'?'منشور':x.status==='draft'?'مسودة':'مجدول'}</span><span><b>${esc(x.title)}</b><small class="meta">${x.reporter?esc(x.reporter):'بدون مراسل'} ${x.featured?' • رئيسي':''} ${x.breaking?' • عاجل':''}</small></span><span class="hide">${esc(x.category)}</span><span class="actions"><button onclick="edit(${x.id})">تعديل</button><button onclick="toggleFeatured(${x.id})">${x.featured?'إلغاء الرئيسي':'رئيسي'}</button><button class="red" onclick="archive(${x.id})">أرشفة</button></span></div>`).join('')+(list.length?'':'<div class="empty">لا توجد مواد مطابقة.</div>')}
function form(){const n=editId?get().find(x=>x.id===editId):{title:'',excerpt:'',body:'',status:'draft',breaking:false,featured:false,category:'محلي',image:'assets/studio.jpg',views:0,time:'الآن',reporter:''};const rs=reps();$('#title').textContent=editId?'تعديل خبر':'خبر جديد';$('#view').innerHTML=`<div class="content"><div class="form"><div class="form-head"><div><h2>${editId?'تعديل الخبر':'إنشاء خبر جديد'}</h2><small>اكتب، ارفع الصورة، ثم اختر حالة النشر.</small></div><span class="live-chip">غرفة الأخبار</span></div><div class="grid"><div class="field full"><label>عنوان الخبر *</label><input id="fTitle" value="${esc(n.title)}" placeholder="عنوان واضح ومباشر"></div><div class="field"><label>التصنيف</label><select id="fCat">${['محلي','السودان','العالم','تغطيات جولة','توثيق','تقارير','مجتمع','فيديو'].map(c=>`<option ${n.category===c?'selected':''}>${c}</option>`).join('')}</select></div><div class="field"><label>الحالة</label><select id="fStatus"><option value="draft" ${n.status==='draft'?'selected':''}>مسودة</option><option value="published" ${n.status==='published'?'selected':''}>منشور</option><option value="scheduled" ${n.status==='scheduled'?'selected':''}>مجدول</option></select></div><div class="field"><label>المراسل</label><select id="fReporter"><option value="">بدون مراسل</option>${rs.map(r=>`<option ${n.reporter===r.name?'selected':''}>${esc(r.name)}</option>`).join('')}</select></div><div class="field"><label>وقت العرض</label><input id="fTime" value="${esc(n.time||'الآن')}" placeholder="الآن / قبل 10 دقائق"></div><div class="field full"><label>الملخص</label><input id="fExcerpt" value="${esc(n.excerpt)}" placeholder="ملخص يظهر في بطاقات الأخبار"></div><div class="field full"><label>نص الخبر</label><textarea id="fBody" placeholder="تفاصيل الخبر...">${esc(n.body)}</textarea></div><div class="field full"><label>صورة الغلاف</label><div class="upload"><input id="fImage" value="${esc(n.image||'assets/studio.jpg')}" placeholder="رابط الصورة أو ارفع من الهاتف"><input id="fFile" type="file" accept="image/*" onchange="previewImage(this)"><img id="preview" src="${esc(n.image||'assets/studio.jpg')}" onerror="this.style.display='none'"></div><small>يفضل صورة أفقية عالية الجودة. في هذه النسخة تحفظ الصورة داخل المتصفح.</small></div></div><div class="checks"><label><input id="fBreaking" type="checkbox" ${n.breaking?'checked':''}> 🔴 نشر كخبر عاجل</label><label><input id="fFeatured" type="checkbox" ${n.featured?'checked':''}> ⭐ وضع في الأخبار الرئيسية</label></div><div class="form-actions"><button class="btn" onclick="saveArticle()">حفظ الخبر</button><button class="btn ghost" onclick="current='articles';editId=null;render()">إلغاء</button></div></div></div>`}
function previewImage(input){const f=input.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{$('#fImage').value=r.result;$('#preview').src=r.result;$('#preview').style.display='block'};r.readAsDataURL(f)}
function saveArticle(){const a=get();const old=editId?a.find(x=>x.id===editId):null;const item={id:editId||Date.now(),title:$('#fTitle').value.trim()||'خبر جديد',category:$('#fCat').value,excerpt:$('#fExcerpt').value.trim(),body:$('#fBody').value.trim(),image:$('#fImage').value.trim()||'assets/studio.jpg',status:$('#fStatus').value,breaking:$('#fBreaking').checked,featured:$('#fFeatured').checked,reporter:$('#fReporter').value,time:$('#fTime').value.trim()||'الآن',views:old?.views||0};if(item.featured){a.forEach(x=>x.featured=false)}if(editId){a[a.findIndex(x=>x.id===editId)]=item}else a.push(item);put(a);current='articles';editId=null;render();}
function edit(id){editId=id;current='new';render()} function archive(id){if(confirm('أرشفة الخبر؟')){put(get().filter(x=>x.id!==id));render()}} function toggleFeatured(id){const a=get();a.forEach(x=>x.featured=x.id===id?!x.featured:false);put(a);render()}
function reporters(){const r=reps();$('#title').textContent='المراسلون';$('#view').innerHTML=`<div class="content"><div class="toolbar"><div><h2>شبكة مراسلي جولة</h2><small>يمكن ربط كل خبر بمراسل.</small></div><button class="btn" onclick="addReporter()">+ مراسل</button></div><div class="panel">${r.map(x=>`<div class="tr rep"><span class="avatar-mini">${esc(x.name.slice(0,1))}</span><span><b>${esc(x.name)}</b><small class="meta">${esc(x.role)} • ${esc(x.region)}</small></span><span class="hide">${x.active?'نشط':'غير نشط'}</span><span><button class="actions-btn" onclick="editReporter(${x.id})">تعديل</button></span></div>`).join('')}</div></div>`}
function addReporter(){const name=prompt('اسم المراسل');if(!name)return;const r=reps();r.push({id:Date.now(),name,role:prompt('الصفة','مراسل جولة')||'مراسل جولة',region:prompt('المنطقة','')||'',active:true});putReps(r);render()}
function editReporter(id){const r=reps();const x=r.find(z=>z.id===id);if(!x)return;x.name=prompt('اسم المراسل',x.name)||x.name;x.role=prompt('الصفة',x.role)||x.role;x.region=prompt('المنطقة',x.region)||x.region;putReps(r);render()}
boot();
